name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
    flutter_animated_text_kit: ^4.2.1
  cupertino_icons: ^1.0.6
  http: ^0.13.4  # Ajout du package http
  image_picker: ^0.8.4+4
  get: ^4.6.1
  shared_preferences: ^2.0.7
  permission_handler: ^10.0.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

flutter:
  assets:
    - assets/Logo1.png
    - assets/Logo2.png
    - assets/Formbackground.png
    - assets/Formbackground2.png
    - assets/Fournisseur.jpg
    - assets/Instagrammeur.jpg
    - assets/Product1.png
    - assets/Product2.png
    - assets/Mixeur.png
    - assets/Cafetiere.jpeg
    - assets/Refrigerateur.png
    - assets/Lave-linge.jpg

  fonts:
    - family: Schyler
      fonts:
        - asset: fonts/Schuyler.ttf
        - asset: fonts/Schuyleritalic.ttf
          style: italic

  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/Icon.png" # Chemin de votre icône personnalisée
